### PR TITLE
Readme and documentation amendments

### PR DESCRIPTION
**Pull request by HeroicKatora**
- All ''color types'' of `image` and more, in particular an interface that will support planar layouts. Interaction with _other_ crates that offer, e.g., exactly the Linux DRM layouts are simplified by flexible write access. (See the `drm` crate in the workspace which is in its infancy, may get offered later when I donate some currently private code with regards to pure-Rust `fblib`/`libdrm` alternatives; I like teasing everyone). 
- Sans-IO approach with largely untyped buffers, but strongly typed view types such that all frames can be stroed in a uniform type while having _optionally_ typesafe interactions in compute functions. The fallback to a byte-based layout guarantees that this isn't restrictive and many forms memory sharing, hardware accelleration, SIMD usage _can_ be applied without requiring explicit library support for each.
- Color conversion is included, in a very rough draft that mostly works but requires some work on the interface and error behavior. Also CMYK and ICC will be interesting to add, but seem simple enough. (Note: in an effort to spite web devs, HSL and HSV will *not* be accepted. Jk, but it seriously isn't my focus to make them work).

@fintelia  I'd like to publish this as a first version, soonish. Due to obvious tie-in with your vision of `image-core`, we might steal and then replace all the color model portions at some stage. Also, potentially this fixes the long-standing issues in `image` with regards to conversion.

- [x] Name: `framebuf`, `image-framebuf`, `image-frame` all seems mostly acceptable to me. I have some reservations towards grabbing `framebuf` due to the design space of offering unified OS-interfaces for various system/window manager frame buffers.

### CODE REVIEW

**Comment by fintelia** [comment]
These documentation changes look good to me.

A comment on the overall crate structure: it would be helpful to move many of the public types into submodules so the generated documentation is more approachable and the important types stand out.

**Comment by fintelia** [comment]
These documentation changes look good to me.

A comment on the overall crate structure: it would be helpful to move many of the public types into submodules so the generated documentation is more approachable and the important types stand out.

**Comment by fintelia** [comment]
Naming-wise I'm not 100% sold on "framebuffer". My understanding is that term usually refers to the region in GPU memory that corresponds to pixels on the screen, and not broader cases of storing arrays of pixels

**Comment by HeroicKatora** [comment]
Other naming choices I had considered:

- `image-buffer`: [taken](https://docs.rs/image_buffer/latest/image_buffer/) and sadly nwim disappeared.
- `image-canvas`, doing a switchero and pushing the internals to some other crate name. This might actually be helpful in making the core `Texel`-marker type more accessible.
    - Maybe `texel-buffer` for this other crate?
    - Publish just the `Texel` type in its own crate with separate versioning that can reach a stable `1.0` much sooner.
-

**Comment by HeroicKatora** [comment]
@fintelia So, my gut is telling me:

- Rename the current `image-canvas` to `image-texel`.
- Use the `image-canvas` crate for this instead.

Regarding items being top-level, I don't really want to have too many modules either. `wgpu` thrives despite the top-level approach, but I do see the point about it being less-than-optimal in terms of being approachable. Thus, I would just do two top-level modules:

- `color`: Containing all the color-related details, as is already the case internally
- `layout`: For the layout, LayoutError, `SampleParts`, `Block`, `SampleBits`
- In the top-level, have the container types `Canvas` (renamed from `Frame`), `Plane`, `PlaneRef`, `PlaneMut`

agreed?

**Pull request merged**
